apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-noticias-deployment
spec:
  selector:
    matchLabels:
      app: mysql-noticias
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-noticias
    spec:
      containers:
      - name: mysql-noticias-container
        image: aluracursos/mysql-db:1
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: mysql-configmap
