apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessao
spec:
  storageClassName: "slow"
  resources:
    requests:
      storage: {2:<Size>}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
