apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pv-disk
    fsType: ext4
