apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume
          name: primeiro-pod-sc
  volumes:
    - name: primeiro-pod-sc
      persistentVolumeClaim:
        claimName: pvc-sc
